baseURL = "https://karinani.github.io/"
languageCode = "en-us"
title = "My Personal Website"
theme = "PaperMod"
description = "A simple website built with Hugo and the PaperMod theme."
author = "Karina"

[params]
  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"