baseURL = "https://karinani.github.io/"
languageCode = "en-us"
title = "My Site"
theme = "hugo-PaperMod"

[params]
  env = "production"

[params.profileMode]
  enabled = true
  title = "Karina Nihalani"
  subtitle = "A person with various interests in Computer Science, Machine Learning and Back end Development"
  imageUrl = "/pfpimage.jpg"
  imageTitle = "Your image title"
  imageWidth = 200
  imageHeight = 250

[[params.profileMode.socialIcons]]
  name = "github"
  url = "https://github.com/KarinaNi"

[[params.profileMode.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/Karina1"

[[params.profileMode.buttons]]
  name = "Projects"
  url = "posts"

[[params.profileMode.buttons]]
  name = "About me"
  url = "tags"

[[params.profileMode.buttons]]
  name = "Experience"
  url = "tags"

[[params.profileMode.buttons]]
  name = "Other"
  url = "tags"


